export const SET_MODAL_INGREDIENT = "SET_MODAL_INGREDIENT";
export const RESET_MODAL_INGREDIENT = "RESET_MODAL_INGREDIENT";
export const RESET_ORDER_NUMBER = "RESET_ORDER_NUMBER";
export const SET_VISIBILITY = 'SET_VISIBILITY'
export const REMOVE_VISIBILITY = 'REMOVE_VISIBILITY'
