export const SET_USER_INFO: "SET_USER_INFO" = "SET_USER_INFO";
export const FETCH_AUTH_REQUEST: "FETCH_AUTH_REQUEST" = "FETCH_AUTH_REQUEST";
export const FETCH_AUTH_SUCCESS: "FETCH_AUTH_SUCCESS" = "FETCH_AUTH_SUCCESS";
export const FETCH_AUTH_ERROR: "FETCH_AUTH_ERROR" = "FETCH_AUTH_ERROR";
export const DELETE_USER: "DELETE_USER" = "DELETE_USER";
export const SET_LOGIN_STATUS: "SET_LOGIN_STATUS" = "SET_LOGIN_STATUS";

export const FETCH_REFRESH_TOKEN_REQUEST: "FETCH_REFRESH_TOKEN_REQUEST" = "FETCH_REFRESH_TOKEN_REQUEST";
export const FETCH_REFRESH_TOKEN_SUCCESS: "FETCH_REFRESH_TOKEN_SUCCESS" = "FETCH_REFRESH_TOKEN_SUCCESS";
export const FETCH_REFRESH_TOKEN_ERROR: "FETCH_REFRESH_TOKEN_ERROR" = "FETCH_REFRESH_TOKEN_ERROR";