export const SET_MODAL_INGREDIENT: "SET_MODAL_INGREDIENT" =
  "SET_MODAL_INGREDIENT";
export const RESET_ORDER_NUMBER: "RESET_ORDER_NUMBER" = "RESET_ORDER_NUMBER";
export const SET_VISIBILITY_MODAL_ORDER: "SET_VISIBILITY_MODAL_ORDER" =
  "SET_VISIBILITY_MODAL_ORDER";
export const SET_ORDER_NUMBER_VISIBILITY: "SET_ORDER_NUMBER_VISIBILITY" =
  "SET_ORDER_NUMBER_VISIBILITY";
export const RESET_ORDER_NUMBER_VISIBILITY: "RESET_ORDER_NUMBER_VISIBILITY" =
  "RESET_ORDER_NUMBER_VISIBILITY";
